-- 한국 영화 데이터 업데이트
-- 생성일시: 2025-07-29T12:00:11.528Z
-- 총 영화 수: 24개

INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('발레리나', 'Ballerina', '이충현', ''{"이창윤"}'', 'Drama', null, 93, '한국', '기타 영화. 이충현 감독 작품. 이창윤 주연.', ''{"발레리나","ballerina","이충현","이창윤","기타"}'', '20234688', NULL, '기타');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('야당: 익스텐디드 컷', NULL, '황병국', ''{"강하늘","유해진","박해준","류경수","채원빈"}'', 'Crime', 2025, 136, '한국', '범죄, 액션 영화. 황병국 감독 작품. 강하늘, 유해진, 박해준 주연. 2025-08-06 개봉.', ''{"야당: 익스텐디드 컷","황병국","강하늘","유해진","박해준","류경수","채원빈","범죄, 액션"}'', '20256381', '청소년관람불가', '범죄, 액션');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('서울의 봄', '12.12: THE DAY', '김성수', ''{"황정민","정우성","이성민","박해준","김성균","김의성","정동환","안내상","유성주","최병모"}'', 'Drama', 2023, 141, '한국', '드라마 영화. 김성수 감독 작품. 황정민, 정우성, 이성민 주연. 2023-11-22 개봉.', ''{"서울의 봄","12.12: the day","김성수","황정민","정우성","이성민","박해준","김성균","김의성","정동환","안내상","유성주","최병모","드라마"}'', '20212866', '12세이상관람가', '드라마');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('파묘', 'Exhuma', '장재현', ''{"최민식","김고은","유해진","이도현","김재철","김민준","김병오","전진기","박정자","박지일"}'', 'Mystery', 2024, 133, '한국', '미스터리, 공포(호러) 영화. 장재현 감독 작품. 최민식, 김고은, 유해진 주연. 2024-02-22 개봉.', ''{"파묘","exhuma","장재현","최민식","김고은","유해진","이도현","김재철","김민준","김병오","전진기","박정자","박지일","미스터리, 공포(호러)"}'', '20234675', '15세이상관람가', '미스터리, 공포(호러)');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('범죄도시3', 'THE ROUNDUP : NO WAY OUT', '이상용', ''{"마동석","이준혁","아오키 무네타카","마동석","김병탁","이범수","김민재","이지훈","김도건","고규필"}'', 'Crime', 2023, 105, '한국', '범죄, 액션 영화. 이상용 감독 작품. 마동석, 이준혁, 아오키 무네타카 주연. 2023-05-31 개봉.', ''{"범죄도시3","the roundup : no way out","이상용","마동석","이준혁","아오키 무네타카","마동석","김병탁","이범수","김민재","이지훈","김도건","고규필","범죄, 액션"}'', '20226411', '15세이상관람가', '범죄, 액션');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('콘크리트 유토피아', 'Concrete Utopia', '엄태화', ''{"이병헌","박서준","박보영","김선영","김도윤","박지후","김학선","공민정","엄태구","정영기"}'', 'Drama', 2023, 129, '한국', '드라마, 기타 영화. 엄태화 감독 작품. 이병헌, 박서준, 박보영 주연. 2023-08-09 개봉.', ''{"콘크리트 유토피아","concrete utopia","엄태화","이병헌","박서준","박보영","김선영","김도윤","박지후","김학선","공민정","엄태구","정영기","드라마, 기타"}'', '20204264', '15세이상관람가', '드라마, 기타');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('투더문', NULL, NULL, ''{}'', 'Drama', null, NULL, '한국', NULL, ''{"투더문"}'', '20253263', NULL, NULL);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('밀수', 'Smugglers', '류승완', ''{"김혜수","염정아","조인성","박정민","김종수","고민시","김재화","박준면","박경혜","주보비"}'', 'Action', 2023, 129, '한국', '액션 영화. 류승완 감독 작품. 김혜수, 염정아, 조인성 주연. 2023-07-26 개봉.', ''{"밀수","smugglers","류승완","김혜수","염정아","조인성","박정민","김종수","고민시","김재화","박준면","박경혜","주보비","액션"}'', '20218541', '15세이상관람가', '액션');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('대탈출 : 더 스토리 특별판', 'The Great Escape : The Story', NULL, ''{}'', 'Adventure', 2025, 121, '한국', '어드벤처, 미스터리, 스릴러 영화. 2025-07-23 개봉.', ''{"대탈출 : 더 스토리 특별판","the great escape : the story","어드벤처, 미스터리, 스릴러"}'', '20256032', '15세이상관람가', '어드벤처, 미스터리, 스릴러');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('노량: 죽음의 바다', 'Noryang: Deadly Sea', '김한민', ''{"김윤석","백윤식","정재영","허준호","김성규","이규형","이무생","최덕문","안보현","박명훈"}'', 'Historical', 2023, 152, '한국', '사극, 액션 영화. 김한민 감독 작품. 김윤석, 백윤식, 정재영 주연. 2023-12-20 개봉.', ''{"노량: 죽음의 바다","noryang: deadly sea","김한민","김윤석","백윤식","정재영","허준호","김성규","이규형","이무생","최덕문","안보현","박명훈","사극, 액션"}'', '20203702', '12세이상관람가', '사극, 액션');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('웅남이', 'woongnami', '박성광', ''{"박성웅","최민수","오달수","염혜란","이이경","윤제문","백지혜","서동원","한다솔","정우성"}'', 'Comedy', 2023, 97, '한국', '코미디, 액션 영화. 박성광 감독 작품. 박성웅, 최민수, 오달수 주연. 2023-03-22 개봉.', ''{"웅남이","woongnami","박성광","박성웅","최민수","오달수","염혜란","이이경","윤제문","백지혜","서동원","한다솔","정우성","코미디, 액션"}'', '20210544', '15세이상관람가', '코미디, 액션');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('천박사 퇴마 연구소: 설경의 비밀', 'Dr. Cheon And The Lost Talisman', '김성식', ''{"강동원","허준호","이솜","이동휘","김종수","박소이","윤병희","주보비","박경혜","이규호"}'', 'Fantasy', 2023, 98, '한국', '판타지, 액션 영화. 김성식 감독 작품. 강동원, 허준호, 이솜 주연. 2023-09-27 개봉.', ''{"천박사 퇴마 연구소: 설경의 비밀","dr. cheon and the lost talisman","김성식","강동원","허준호","이솜","이동휘","김종수","박소이","윤병희","주보비","박경혜","이규호","판타지, 액션"}'', '20227410', '12세이상관람가', '판타지, 액션');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('보호자', 'A Man of Reason', '정우성', ''{"정우성","김남길","김준한","박성웅","박유나","이엘리야","류지안","박성준","문성환","김주헌"}'', 'Action', 2023, 97, '한국', '액션, 드라마 영화. 정우성 감독 작품. 정우성, 김남길, 김준한 주연. 2023-08-15 개봉.', ''{"보호자","a man of reason","정우성","정우성","김남길","김준한","박성웅","박유나","이엘리야","류지안","박성준","문성환","김주헌","액션, 드라마"}'', '20192995', '15세이상관람가', '액션, 드라마');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('30일', 'Love Reset', '남대중', ''{"강하늘","정소민","조민수","김선영","황세인","윤경호","이상진","원우","송해나","엄지윤"}'', 'Comedy', 2023, 119, '한국', '코미디 영화. 남대중 감독 작품. 강하늘, 정소민, 조민수 주연. 2023-10-03 개봉.', ''{"30일","love reset","남대중","강하늘","정소민","조민수","김선영","황세인","윤경호","이상진","원우","송해나","엄지윤","코미디"}'', '20228819', '12세이상관람가', '코미디');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('우리는 민주화란 필름으로', NULL, NULL, ''{}'', 'Drama', null, 2, '한국', '드라마 영화.', ''{"우리는 민주화란 필름으로","드라마"}'', '20249148', NULL, '드라마');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('귀공자', 'The Childe', '박훈정', ''{"김선호","강태주","김강우","고아라","양이겸","정예지","손정아","김한솔"}'', 'Action', 2023, 117, '한국', '액션 영화. 박훈정 감독 작품. 김선호, 강태주, 김강우 주연. 2023-06-21 개봉.', ''{"귀공자","the childe","박훈정","김선호","강태주","김강우","고아라","양이겸","정예지","손정아","김한솔","액션"}'', '20211937', '청소년관람불가', '액션');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('악마들', 'Devils', '김재훈', ''{"장동윤","오대환","최귀화","장재호","손종학","신승환","윤병희","이상원","왕지혜","김태겸"}'', 'Action', 2023, 105, '한국', '액션, 스릴러 영화. 김재훈 감독 작품. 장동윤, 오대환, 최귀화 주연. 2023-07-05 개봉.', ''{"악마들","devils","김재훈","장동윤","오대환","최귀화","장재호","손종학","신승환","윤병희","이상원","왕지혜","김태겸","액션, 스릴러"}'', '20224579', '청소년관람불가', '액션, 스릴러');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('플리에 & 리바운드', 'Plie & Rebound', NULL, ''{}'', 'Animation', null, 6, '한국', '애니메이션 영화.', ''{"플리에 & 리바운드","plie & rebound","애니메이션"}'', '20248504', NULL, '애니메이션');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('킬링 로맨스', 'Killing Romance', '이원석', ''{"이하늬","이선균","공명","배유람","심달기","최준규","신민재","주광현","최덕문","오정세"}'', 'Comedy', 2023, 107, '한국', '코미디 영화. 이원석 감독 작품. 이하늬, 이선균, 공명 주연. 2023-04-14 개봉.', ''{"킬링 로맨스","killing romance","이원석","이하늬","이선균","공명","배유람","심달기","최준규","신민재","주광현","최덕문","오정세","코미디"}'', '20200154', '15세이상관람가', '코미디');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('소울메이트', 'Soulmate', '민용근', ''{"김다미","전소니","변우석","장혜진","박충선","허지나","박성연","김새벽","류지안","강말금"}'', 'Drama', 2023, 123, '한국', '드라마 영화. 민용근 감독 작품. 김다미, 전소니, 변우석 주연. 2023-03-15 개봉.', ''{"소울메이트","soulmate","민용근","김다미","전소니","변우석","장혜진","박충선","허지나","박성연","김새벽","류지안","강말금","드라마"}'', '20197654', '12세이상관람가', '드라마');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('비공식작전', 'Ransomed', '김성훈', ''{"하정우","주지훈","권은성","임형국","김응수","김종수","박혁권","유승목","한수현","최정우"}'', 'Drama', 2023, 132, '한국', '드라마 영화. 김성훈 감독 작품. 하정우, 주지훈, 권은성 주연. 2023-08-02 개봉.', ''{"비공식작전","ransomed","김성훈","하정우","주지훈","권은성","임형국","김응수","김종수","박혁권","유승목","한수현","최정우","드라마"}'', '20193879', '12세이상관람가', '드라마');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('댓글부대', 'Troll Factory', '안국진', ''{"손석구","김성철","김동휘","홍경","이찬유","김한솔","손희서","박상혁","윤덕용","이현"}'', 'Crime', 2024, 109, '한국', '범죄, 드라마 영화. 안국진 감독 작품. 손석구, 김성철, 김동휘 주연. 2024-03-27 개봉.', ''{"댓글부대","troll factory","안국진","손석구","김성철","김동휘","홍경","이찬유","김한솔","손희서","박상혁","윤덕용","이현","범죄, 드라마"}'', '20231041', '15세이상관람가', '범죄, 드라마');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('하이재킹', 'Hijack 1971', '김성한', ''{"하정우","여진구","성동일","채수빈","문유강","임형택","전정관","정예진","문우진","홍정혜"}'', 'Crime', 2024, 100, '한국', '범죄, 액션 영화. 김성한 감독 작품. 하정우, 여진구, 성동일 주연. 2024-06-21 개봉.', ''{"하이재킹","hijack 1971","김성한","하정우","여진구","성동일","채수빈","문유강","임형택","전정관","정예진","문우진","홍정혜","범죄, 액션"}'', '20248465', '12세이상관람가', '범죄, 액션');
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, description, keywords, kofic_movie_code, watch_grade, genres_korean) VALUES ('탈주', 'Escape', '이종필', ''{"이제훈","구교환","홍사빈","서현우","이성욱","정준원","장영남","송강","이솜","이호정"}'', 'Action', 2024, 94, '한국', '액션 영화. 이종필 감독 작품. 이제훈, 구교환, 홍사빈 주연. 2024-07-03 개봉.', ''{"탈주","escape","이종필","이제훈","구교환","홍사빈","서현우","이성욱","정준원","장영남","송강","이솜","이호정","액션"}'', '20212932', '12세이상관람가', '액션');
