-- 실제 한국/해외 영화 데이터 (2003-2024)
-- 기생충, 파묘, 범죄도시 시리즈, 마블/DC 영화 등 실제 작품들

-- 영화 데이터 인서트
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('파묘', 'Exhuma', '장재현', '{"최민식","김고은","유해진","이도현"}', 'Horror', 2024, 106, 'South Korea', 9.3, '긴장감 넘치는 스토리와 뛰어난 연출로 공포 영화의 새로운 장을 연 장재현 감독의 작품이다.', '{"파묘","장재현","최민식","Horror","2024"}', NULL, 137420);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('범죄도시4', 'The Roundup: Punishment', '허명행', '{"마동석","김무열","이동휘"}', 'Action', 2024, 142, 'South Korea', 9.1, 'Action 장르의 대작으로, 허명행 감독의 연출과 마동석의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"범죄도시4","허명행","마동석","Action","2024"}', NULL, 485874);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('서울의 봄', 'Seoul Spring', '김성수', '{"황정민","정우성","이성민"}', 'Drama', 2023, 117, 'South Korea', 7.3, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 김성수 감독의 대표작으로, 황정민의 뛰어난 연기가 인상적이다.', '{"서울의 봄","김성수","황정민","Drama","2023"}', NULL, 600473);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('스즈메의 문단속', 'Suzume', '신카이 마코토', '{"하라 나나미","마츠무라 호쿠토"}', 'Animation', 2023, 102, 'South Korea', 8.9, '뛰어난 애니메이션 기술과 감동적인 스토리가 조화를 이룬 신카이 마코토 감독의 애니메이션 작품이다.', '{"스즈메의 문단속","신카이 마코토","하라 나나미","Animation","2023"}', NULL, 860796);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('아바타: 물의 길', '아바타: 물의 길', '제임스 카메론', '{"샘 워딩턴","조 샐다나"}', 'Science Fiction', 2022, 135, 'South Korea', 7.6, '미래적 상상력과 첨단 기술이 결합된 제임스 카메론 감독의 SF 블록버스터이다.', '{"아바타: 물의 길","제임스 카메론","샘 워딩턴","Science Fiction","2022"}', NULL, 139999);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('스파이더맨: 어크로스 더 유니버스', '스파이더맨: 어크로스 더 유니버스', '호아킴 도스 산토스', '{"샤메익 무어","헤일리 스타인펠드"}', 'Animation', 2023, 96, 'South Korea', 7.7, '뛰어난 애니메이션 기술과 감동적인 스토리가 조화를 이룬 호아킴 도스 산토스 감독의 애니메이션 작품이다.', '{"스파이더맨: 어크로스 더 유니버스","호아킴 도스 산토스","샤메익 무어","Animation","2023"}', NULL, 707009);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('가디언즈 오브 갤럭시 VOL. 3', '가디언즈 오브 갤럭시 VOL. 3', '제임스 건', '{"크리스 프랫","조 샐다나"}', 'Action', 2023, 125, 'South Korea', 7.3, 'Action 장르의 대작으로, 제임스 건 감독의 연출과 크리스 프랫의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"가디언즈 오브 갤럭시 VOL. 3","제임스 건","크리스 프랫","Action","2023"}', NULL, 1054817);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('인디아나 존스: 운명의 다이얼', '인디아나 존스: 운명의 다이얼', '제임스 맨골드', '{"해리슨 포드","피비 윌러-브리지"}', 'Adventure', 2023, 115, 'South Korea', 7.2, '제임스 맨골드 감독의 대표작 중 하나로 평가받는 수작이다.', '{"인디아나 존스: 운명의 다이얼","제임스 맨골드","해리슨 포드","Adventure","2023"}', NULL, 565559);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('분노의 질주: 라이드 오어 다이', '분노의 질주: 라이드 오어 다이', '루이스 레테리어', '{"빈 디젤","미셸 로드리게스"}', 'Action', 2023, 143, 'South Korea', 7.2, 'Action 장르의 대작으로, 루이스 레테리어 감독의 연출과 빈 디젤의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"분노의 질주: 라이드 오어 다이","루이스 레테리어","빈 디젤","Action","2023"}', NULL, 367294);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('더 슈퍼 마리오 브라더스 무비', '더 슈퍼 마리오 브라더스 무비', '아론 호바스', '{"크리스 프랫","안야 테일러조이"}', 'Animation', 2023, 109, 'South Korea', 9.0, '뛰어난 애니메이션 기술과 감동적인 스토리가 조화를 이룬 아론 호바스 감독의 애니메이션 작품이다.', '{"더 슈퍼 마리오 브라더스 무비","아론 호바스","크리스 프랫","Animation","2023"}', NULL, 379829);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('존 윅 4', '존 윅 4', '채드 스타헬스키', '{"키아누 리브스","도니 옌"}', 'Action', 2023, 123, 'South Korea', 7.7, 'Action 장르의 대작으로, 채드 스타헬스키 감독의 연출과 키아누 리브스의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"존 윅 4","채드 스타헬스키","키아누 리브스","Action","2023"}', NULL, 590639);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('오펜하이머', '오펜하이머', '크리스토퍼 놀란', '{"킬리언 머피","에밀리 블런트"}', 'Drama', 2023, 148, 'South Korea', 7.6, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 크리스토퍼 놀란 감독의 대표작으로, 킬리언 머피의 뛰어난 연기가 인상적이다.', '{"오펜하이머","크리스토퍼 놀란","킬리언 머피","Drama","2023"}', NULL, 543644);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('바비', '바비', '그레타 거윅', '{"마고 로비","라이언 고슬링"}', 'Comedy', 2023, 104, 'South Korea', 8.4, '유쾌하고 재치있는 스토리로 관객들에게 웃음을 선사하는 그레타 거윅 감독의 코미디 영화이다.', '{"바비","그레타 거윅","마고 로비","Comedy","2023"}', NULL, 856580);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('탑건: 매버릭', '탑건: 매버릭', '조셉 코신스키', '{"톰 크루즈","마일스 텔러"}', 'Action', 2022, 147, 'South Korea', 8.2, 'Action 장르의 대작으로, 조셉 코신스키 감독의 연출과 톰 크루즈의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"탑건: 매버릭","조셉 코신스키","톰 크루즈","Action","2022"}', NULL, 1011830);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('토르: 러브 앤 썬더', '토르: 러브 앤 썬더', '타이카 와이티티', '{"크리스 헴스워스","나탈리 포트만"}', 'Action', 2022, 131, 'South Korea', 7.2, 'Action 장르의 대작으로, 타이카 와이티티 감독의 연출과 크리스 헴스워스의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"토르: 러브 앤 썬더","타이카 와이티티","크리스 헴스워스","Action","2022"}', NULL, 259749);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('닥터 스트레인지: 대혼돈의 멀티버스', '닥터 스트레인지: 대혼돈의 멀티버스', '샘 레이미', '{"베네딕트 컴버배치","엘리자베스 올슨"}', 'Action', 2022, 147, 'South Korea', 9.1, 'Action 장르의 대작으로, 샘 레이미 감독의 연출과 베네딕트 컴버배치의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"닥터 스트레인지: 대혼돈의 멀티버스","샘 레이미","베네딕트 컴버배치","Action","2022"}', NULL, 824333);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('미니언즈: 라이즈 오브 그루', '미니언즈: 라이즈 오브 그루', '카일 발다', '{"스티브 카렐","피에르 코팽"}', 'Animation', 2022, 104, 'South Korea', 8.5, '뛰어난 애니메이션 기술과 감동적인 스토리가 조화를 이룬 카일 발다 감독의 애니메이션 작품이다.', '{"미니언즈: 라이즈 오브 그루","카일 발다","스티브 카렐","Animation","2022"}', NULL, 725505);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('엘비스', '엘비스', '바즈 루어만', '{"오스틴 버틀러","톰 행크스"}', 'Drama', 2022, 126, 'South Korea', 7.3, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 바즈 루어만 감독의 대표작으로, 오스틴 버틀러의 뛰어난 연기가 인상적이다.', '{"엘비스","바즈 루어만","오스틴 버틀러","Drama","2022"}', NULL, 742122);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('쥬라기 월드: 도미니언', '쥬라기 월드: 도미니언', '콜린 트레보로우', '{"크리스 프랫","브라이스 달라스 하워드"}', 'Adventure', 2022, 115, 'South Korea', 7.0, '콜린 트레보로우 감독의 대표작 중 하나로 평가받는 수작이다.', '{"쥬라기 월드: 도미니언","콜린 트레보로우","크리스 프랫","Adventure","2022"}', NULL, 829282);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('범죄도시2', 'The Roundup', '이상용', '{"마동석","손석구"}', 'Action', 2022, 148, 'South Korea', 9.2, 'Action 장르의 대작으로, 이상용 감독의 연출과 마동석의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"범죄도시2","이상용","마동석","Action","2022"}', NULL, 449631);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('헤어질 결심', 'Decision to Leave', '박찬욱', '{"박해일","탕웨이"}', 'Romance', 2022, 107, 'South Korea', 7.4, '아름다운 사랑 이야기를 섬세하게 그려낸 박찬욱 감독의 로맨틱 드라마이다.', '{"헤어질 결심","박찬욱","박해일","Romance","2022"}', NULL, 1066251);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('한산: 용의 출현', 'Hansan: Rising Dragon', '김한민', '{"박해일","변요한"}', 'Drama', 2022, 113, 'South Korea', 7.0, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 김한민 감독의 대표작으로, 박해일의 뛰어난 연기가 인상적이다.', '{"한산: 용의 출현","김한민","박해일","Drama","2022"}', NULL, 550522);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('브로커', 'Broker', '고레에다 히로카즈', '{"송강호","강동원"}', 'Drama', 2022, 125, 'South Korea', 7.3, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 고레에다 히로카즈 감독의 대표작으로, 송강호의 뛰어난 연기가 인상적이다.', '{"브로커","고레에다 히로카즈","송강호","Drama","2022"}', NULL, 324246);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('스파이더맨: 노 웨이 홈', '스파이더맨: 노 웨이 홈', '존 왓츠', '{"톰 홀랜드","젠데이아"}', 'Action', 2021, 122, 'South Korea', 7.4, 'Action 장르의 대작으로, 존 왓츠 감독의 연출과 톰 홀랜드의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"스파이더맨: 노 웨이 홈","존 왓츠","톰 홀랜드","Action","2021"}', NULL, 458601);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('듄', '듄', '드니 빌뇌브', '{"티모시 샬라메","레베카 퍼거슨"}', 'Science Fiction', 2021, 129, 'South Korea', 7.5, '미래적 상상력과 첨단 기술이 결합된 드니 빌뇌브 감독의 SF 블록버스터이다.', '{"듄","드니 빌뇌브","티모시 샬라메","Science Fiction","2021"}', NULL, 1096114);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('007 노 타임 투 다이', '007 노 타임 투 다이', '캐리 후쿠나가', '{"다니엘 크레이그","레아 세두"}', 'Action', 2021, 123, 'South Korea', 7.5, 'Action 장르의 대작으로, 캐리 후쿠나가 감독의 연출과 다니엘 크레이그의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"007 노 타임 투 다이","캐리 후쿠나가","다니엘 크레이그","Action","2021"}', NULL, 264279);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('분노의 질주: 더 얼티메이트', '분노의 질주: 더 얼티메이트', '저스틴 린', '{"빈 디젤","미셸 로드리게스"}', 'Action', 2021, 136, 'South Korea', 7.3, 'Action 장르의 대작으로, 저스틴 린 감독의 연출과 빈 디젤의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"분노의 질주: 더 얼티메이트","저스틴 린","빈 디젤","Action","2021"}', NULL, 784856);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('이터널스', '이터널스', '클로이 자오', '{"젬마 찬","리처드 매든"}', 'Action', 2021, 141, 'South Korea', 8.3, 'Action 장르의 대작으로, 클로이 자오 감독의 연출과 젬마 찬의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"이터널스","클로이 자오","젬마 찬","Action","2021"}', NULL, 713967);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('베놈 2: 렛 데어 비 카니지', '베놈 2: 렛 데어 비 카니지', '앤디 서키스', '{"톰 하디","우디 해럴슨"}', 'Action', 2021, 129, 'South Korea', 8.5, 'Action 장르의 대작으로, 앤디 서키스 감독의 연출과 톰 하디의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"베놈 2: 렛 데어 비 카니지","앤디 서키스","톰 하디","Action","2021"}', NULL, 301153);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('매트릭스 4: 리저렉션', '매트릭스 4: 리저렉션', '라나 워쇼스키', '{"키아누 리브스","캐리 앤 모스"}', 'Science Fiction', 2021, 159, 'South Korea', 9.0, '미래적 상상력과 첨단 기술이 결합된 라나 워쇼스키 감독의 SF 블록버스터이다.', '{"매트릭스 4: 리저렉션","라나 워쇼스키","키아누 리브스","Science Fiction","2021"}', NULL, 326863);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('기생충', 'Parasite', '봉준호', '{"송강호","이선균","조여정","최우식"}', 'Thriller', 2019, 118, 'South Korea', 9.3, '긴장감 넘치는 스토리와 예측불가능한 전개로 관객들을 몰입시키는 봉준호 감독의 스릴러이다.', '{"기생충","봉준호","송강호","Thriller","2019"}', NULL, 265698);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('미나리', 'Minari', '리 아이작 정', '{"스티븐 연","한예리","윤여정"}', 'Drama', 2020, 147, 'South Korea', 7.7, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 리 아이작 정 감독의 대표작으로, 스티븐 연의 뛰어난 연기가 인상적이다.', '{"미나리","리 아이작 정","스티븐 연","Drama","2020"}', NULL, 894162);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('모가디슈', 'Escape from Mogadishu', '류승완', '{"김윤석","조인성"}', 'Drama', 2021, 139, 'South Korea', 9.0, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 류승완 감독의 대표작으로, 김윤석의 뛰어난 연기가 인상적이다.', '{"모가디슈","류승완","김윤석","Drama","2021"}', NULL, 796653);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('어벤져스: 엔드게임', '어벤져스: 엔드게임', '안소니 루소', '{"로버트 다우니 주니어","크리스 에반스"}', 'Action', 2019, 147, 'South Korea', 9.2, 'Action 장르의 대작으로, 안소니 루소 감독의 연출과 로버트 다우니 주니어의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"어벤져스: 엔드게임","안소니 루소","로버트 다우니 주니어","Action","2019"}', NULL, 1011430);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('겨울왕국 2', '겨울왕국 2', '크리스 벅', '{"크리스틴 벨","이디나 멘젤"}', 'Animation', 2019, 86, 'South Korea', 7.8, '뛰어난 애니메이션 기술과 감동적인 스토리가 조화를 이룬 크리스 벅 감독의 애니메이션 작품이다.', '{"겨울왕국 2","크리스 벅","크리스틴 벨","Animation","2019"}', NULL, 733869);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('남산의 부장들', 'The Man from Nowhere', '우민호', '{"이병헌","이성민"}', 'Drama', 2020, 125, 'South Korea', 8.1, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 우민호 감독의 대표작으로, 이병헌의 뛰어난 연기가 인상적이다.', '{"남산의 부장들","우민호","이병헌","Drama","2020"}', NULL, 1015928);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('테넷', '테넷', '크리스토퍼 놀란', '{"존 데이비드 워싱턴","로버트 패틴슨"}', 'Science Fiction', 2020, 155, 'South Korea', 7.1, '미래적 상상력과 첨단 기술이 결합된 크리스토퍼 놀란 감독의 SF 블록버스터이다.', '{"테넷","크리스토퍼 놀란","존 데이비드 워싱턴","Science Fiction","2020"}', NULL, 1037198);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('원더 우먼 1984', '원더 우먼 1984', '패티 젠킨스', '{"갤 가돗","크리스 파인"}', 'Action', 2020, 131, 'South Korea', 8.3, 'Action 장르의 대작으로, 패티 젠킨스 감독의 연출과 갤 가돗의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"원더 우먼 1984","패티 젠킨스","갤 가돗","Action","2020"}', NULL, 857222);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('블랙 위도우', '블랙 위도우', '케이트 쇼틀랜드', '{"스칼릿 요한슨","플로렌스 퓨"}', 'Action', 2021, 133, 'South Korea', 9.2, 'Action 장르의 대작으로, 케이트 쇼틀랜드 감독의 연출과 스칼릿 요한슨의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"블랙 위도우","케이트 쇼틀랜드","스칼릿 요한슨","Action","2021"}', NULL, 330104);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('샹치와 텐 링즈의 전설', '샹치와 텐 링즈의 전설', '데스틴 다니엘 크레튼', '{"시무 리우","어콰피나"}', 'Action', 2021, 142, 'South Korea', 8.1, 'Action 장르의 대작으로, 데스틴 다니엘 크레튼 감독의 연출과 시무 리우의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"샹치와 텐 링즈의 전설","데스틴 다니엘 크레튼","시무 리우","Action","2021"}', NULL, 572370);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('올드보이', 'Oldboy', '박찬욱', '{"최민식","유지태"}', 'Thriller', 2003, 137, 'South Korea', 8.8, '긴장감 넘치는 스토리와 예측불가능한 전개로 관객들을 몰입시키는 박찬욱 감독의 스릴러이다.', '{"올드보이","박찬욱","최민식","Thriller","2003"}', NULL, 647843);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('아가씨', 'The Handmaiden', '박찬욱', '{"김민희","김태리"}', 'Drama', 2016, 112, 'South Korea', 7.3, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 박찬욱 감독의 대표작으로, 김민희의 뛰어난 연기가 인상적이다.', '{"아가씨","박찬욱","김민희","Drama","2016"}', NULL, 673028);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('곡성', 'The Wailing', '나홍진', '{"곽도원","황정민"}', 'Horror', 2016, 100, 'South Korea', 9.2, '긴장감 넘치는 스토리와 뛰어난 연출로 공포 영화의 새로운 장을 연 나홍진 감독의 작품이다.', '{"곡성","나홍진","곽도원","Horror","2016"}', NULL, 633908);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('마더', 'Mother', '봉준호', '{"김혜자","원빈"}', 'Drama', 2009, 117, 'South Korea', 9.2, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 봉준호 감독의 대표작으로, 김혜자의 뛰어난 연기가 인상적이다.', '{"마더","봉준호","김혜자","Drama","2009"}', NULL, 334551);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('추격자', 'The Chaser', '나홍진', '{"김윤석","하정우"}', 'Thriller', 2008, 124, 'South Korea', 7.9, '긴장감 넘치는 스토리와 예측불가능한 전개로 관객들을 몰입시키는 나홍진 감독의 스릴러이다.', '{"추격자","나홍진","김윤석","Thriller","2008"}', NULL, 449551);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('악마를 보았다', 'I Saw the Devil', '김지운', '{"이병헌","최민식"}', 'Thriller', 2010, 123, 'South Korea', 8.1, '긴장감 넘치는 스토리와 예측불가능한 전개로 관객들을 몰입시키는 김지운 감독의 스릴러이다.', '{"악마를 보았다","김지운","이병헌","Thriller","2010"}', NULL, 323482);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('신세계', 'New World', '박훈정', '{"이정재","최민식"}', 'Crime', 2013, 115, 'South Korea', 7.6, '박훈정 감독의 대표작 중 하나로 평가받는 수작이다.', '{"신세계","박훈정","이정재","Crime","2013"}', NULL, 654328);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('베테랑', 'Veteran', '류승완', '{"황정민","유아인"}', 'Action', 2015, 125, 'South Korea', 9.1, 'Action 장르의 대작으로, 류승완 감독의 연출과 황정민의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"베테랑","류승완","황정민","Action","2015"}', NULL, 774725);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('터널', 'Tunnel', '김성훈', '{"하정우","배두나"}', 'Drama', 2016, 135, 'South Korea', 8.0, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 김성훈 감독의 대표작으로, 하정우의 뛰어난 연기가 인상적이다.', '{"터널","김성훈","하정우","Drama","2016"}', NULL, 543199);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('1987', '1987: When the Day Comes', '장준환', '{"김윤석","하정우"}', 'Drama', 2017, 124, 'South Korea', 7.2, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 장준환 감독의 대표작으로, 김윤석의 뛰어난 연기가 인상적이다.', '{"1987","장준환","김윤석","Drama","2017"}', NULL, 438863);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('택시운전사', 'A Taxi Driver', '장훈', '{"송강호","토마스 크레치만"}', 'Drama', 2017, 141, 'South Korea', 7.8, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 장훈 감독의 대표작으로, 송강호의 뛰어난 연기가 인상적이다.', '{"택시운전사","장훈","송강호","Drama","2017"}', NULL, 1079129);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('신과함께-죄와 벌', 'Along with the Gods', '김용화', '{"하정우","차태현"}', 'Fantasy', 2017, 115, 'South Korea', 8.0, '김용화 감독의 대표작 중 하나로 평가받는 수작이다.', '{"신과함께-죄와 벌","김용화","하정우","Fantasy","2017"}', NULL, 729785);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('극한직업', 'Extreme Job', '이병헌', '{"류승룡","이하늬"}', 'Comedy', 2019, 108, 'South Korea', 7.6, '유쾌하고 재치있는 스토리로 관객들에게 웃음을 선사하는 이병헌 감독의 코미디 영화이다.', '{"극한직업","이병헌","류승룡","Comedy","2019"}', NULL, 275298);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('82년생 김지영', 'Kim Ji-young: Born 1982', '김도영', '{"정유미","공유"}', 'Drama', 2019, 120, 'South Korea', 9.1, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 김도영 감독의 대표작으로, 정유미의 뛰어난 연기가 인상적이다.', '{"82년생 김지영","김도영","정유미","Drama","2019"}', NULL, 268672);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('반도', 'Peninsula', '연상호', '{"강동원","이정현"}', 'Action', 2020, 133, 'South Korea', 8.2, 'Action 장르의 대작으로, 연상호 감독의 연출과 강동원의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"반도","연상호","강동원","Action","2020"}', NULL, 221667);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('승리호', 'Space Sweepers', '조성희', '{"송중기","김태리"}', 'Science Fiction', 2021, 136, 'South Korea', 8.5, '미래적 상상력과 첨단 기술이 결합된 조성희 감독의 SF 블록버스터이다.', '{"승리호","조성희","송중기","Science Fiction","2021"}', NULL, 943834);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('기적', 'Miracle', '이장훈', '{"박정민","임윤아"}', 'Drama', 2021, 110, 'South Korea', 7.1, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 이장훈 감독의 대표작으로, 박정민의 뛰어난 연기가 인상적이다.', '{"기적","이장훈","박정민","Drama","2021"}', NULL, 794933);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('연애 빠진 로맨스', '연애 빠진 로맨스', '정기훈', '{"이선빈","이진욱"}', 'Romance', 2021, 112, 'South Korea', 8.4, '아름다운 사랑 이야기를 섬세하게 그려낸 정기훈 감독의 로맨틱 드라마이다.', '{"연애 빠진 로맨스","정기훈","이선빈","Romance","2021"}', NULL, 771640);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('마녀2', 'The Witch: Part 2', '박훈정', '{"신시아","박은빈"}', 'Action', 2022, 145, 'South Korea', 9.0, 'Action 장르의 대작으로, 박훈정 감독의 연출과 신시아의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"마녀2","박훈정","신시아","Action","2022"}', NULL, 272890);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('외계+인 1부', 'Alienoid', '최동훈', '{"류준열","김우빈"}', 'Science Fiction', 2022, 150, 'South Korea', 7.0, '미래적 상상력과 첨단 기술이 결합된 최동훈 감독의 SF 블록버스터이다.', '{"외계+인 1부","최동훈","류준열","Science Fiction","2022"}', NULL, 1096310);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('인생은 아름다워', '인생은 아름다워', '최국희', '{"류승룡","염정아"}', 'Drama', 2022, 146, 'South Korea', 8.7, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 최국희 감독의 대표작으로, 류승룡의 뛰어난 연기가 인상적이다.', '{"인생은 아름다워","최국희","류승룡","Drama","2022"}', NULL, 1053546);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('헌트', 'Hunt', '이정재', '{"이정재","정우성"}', 'Action', 2022, 146, 'South Korea', 7.9, 'Action 장르의 대작으로, 이정재 감독의 연출과 이정재의 뛰어난 액션 연기가 돋보이는 작품이다.', '{"헌트","이정재","이정재","Action","2022"}', NULL, 457338);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('결백', 'Innocence', '박상현', '{"신혜선","배종옥"}', 'Drama', 2020, 110, 'South Korea', 8.7, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 박상현 감독의 대표작으로, 신혜선의 뛰어난 연기가 인상적이다.', '{"결백","박상현","신혜선","Drama","2020"}', NULL, 908904);
INSERT INTO movies (title, english_title, director, cast_members, genre, release_year, runtime_minutes, country, naver_rating, description, keywords, poster_url, naver_movie_id) VALUES ('아이캔스피크', 'I Can Speak', '김현석', '{"나문희","이제훈"}', 'Drama', 2017, 149, 'South Korea', 9.0, '인간의 감정과 사회적 이슈를 깊이 있게 다룬 김현석 감독의 대표작으로, 나문희의 뛰어난 연기가 인상적이다.', '{"아이캔스피크","김현석","나문희","Drama","2017"}', NULL, 708670);

-- 리뷰 데이터 인서트
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (1, '최영화리뷰어', '파묘의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (1, '한국영화평론가', '완성도 높은 작품입니다. 파묘의 모든 요소가 조화롭게 어우러져 있어요.', 9.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (1, '김영화평론가', '파묘는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (1, '최영화리뷰어', '기대 이상의 작품이었어요. 파묘는 시간 가는 줄 모르고 봤네요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (1, '서울영화리뷰', '파묘의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (1, '정시네필', '파묘의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 9.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (1, '박시네마리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 파묘 정말 볼만해요.', 8.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (2, '박시네마리뷰', '범죄도시4, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (2, '한국영화평론가', '범죄도시4, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 9.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (2, '김영화평론가', '범죄도시4의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (2, '박시네마리뷰', '범죄도시4, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (2, '한국영화평론가', '범죄도시4의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 9.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (2, '한국영화평론가', '기대 이상의 작품이었어요. 범죄도시4는 시간 가는 줄 모르고 봤네요.', 8.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (3, '서울영화리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 서울의 봄 정말 볼만해요.', 8.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (3, '이무비크리틱', '서울의 봄, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (3, '정시네필', '올해 최고의 영화 중 하나라고 생각합니다. 서울의 봄 정말 볼만해요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (3, '이무비크리틱', '완성도 높은 작품입니다. 서울의 봄의 모든 요소가 조화롭게 어우러져 있어요.', 6.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (3, '영화저널리스트', '서울의 봄, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (3, '최영화리뷰어', '서울의 봄, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 6.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (3, '시네마스코프', '서울의 봄는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (4, '최영화리뷰어', '스즈메의 문단속 강력 추천합니다! 올해 본 영화 중 최고였어요.', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (4, '박시네마리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 스즈메의 문단속 정말 볼만해요.', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (4, '영화저널리스트', '스즈메의 문단속는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 9.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (4, '김영화평론가', '기대 이상의 작품이었어요. 스즈메의 문단속는 시간 가는 줄 모르고 봤네요.', 9.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (4, '영화저널리스트', '스즈메의 문단속, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 9.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (4, '정시네필', '스즈메의 문단속는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 9.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (4, '최영화리뷰어', '스즈메의 문단속는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (5, '영화저널리스트', '아바타: 물의 길의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (5, '김영화평론가', '아바타: 물의 길는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 6.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (5, '영화저널리스트', '기대 이상의 작품이었어요. 아바타: 물의 길는 시간 가는 줄 모르고 봤네요.', 6.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (5, '서울영화리뷰', '기대 이상의 작품이었어요. 아바타: 물의 길는 시간 가는 줄 모르고 봤네요.', 7.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (5, '부산영화평론', '올해 최고의 영화 중 하나라고 생각합니다. 아바타: 물의 길 정말 볼만해요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (6, '정시네필', '올해 최고의 영화 중 하나라고 생각합니다. 스파이더맨: 어크로스 더 유니버스 정말 볼만해요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (6, '이무비크리틱', '기대 이상의 작품이었어요. 스파이더맨: 어크로스 더 유니버스는 시간 가는 줄 모르고 봤네요.', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (6, '최영화리뷰어', '스파이더맨: 어크로스 더 유니버스는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (6, '부산영화평론', '기대 이상의 작품이었어요. 스파이더맨: 어크로스 더 유니버스는 시간 가는 줄 모르고 봤네요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (6, '이무비크리틱', '스파이더맨: 어크로스 더 유니버스의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (6, '서울영화리뷰', '스파이더맨: 어크로스 더 유니버스 강력 추천합니다! 올해 본 영화 중 최고였어요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (6, '박시네마리뷰', '스파이더맨: 어크로스 더 유니버스 강력 추천합니다! 올해 본 영화 중 최고였어요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (6, '박시네마리뷰', '스파이더맨: 어크로스 더 유니버스는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (6, '정시네필', '완성도 높은 작품입니다. 스파이더맨: 어크로스 더 유니버스의 모든 요소가 조화롭게 어우러져 있어요.', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (7, '최영화리뷰어', '올해 최고의 영화 중 하나라고 생각합니다. 가디언즈 오브 갤럭시 VOL. 3 정말 볼만해요.', 6.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (7, '한국영화평론가', '완성도 높은 작품입니다. 가디언즈 오브 갤럭시 VOL. 3의 모든 요소가 조화롭게 어우러져 있어요.', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (7, '한국영화평론가', '가디언즈 오브 갤럭시 VOL. 3는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 6.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (7, '부산영화평론', '가디언즈 오브 갤럭시 VOL. 3, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (7, '시네마스코프', '완성도 높은 작품입니다. 가디언즈 오브 갤럭시 VOL. 3의 모든 요소가 조화롭게 어우러져 있어요.', 7.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (7, '이무비크리틱', '가디언즈 오브 갤럭시 VOL. 3 강력 추천합니다! 올해 본 영화 중 최고였어요.', 6.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (7, '영화저널리스트', '가디언즈 오브 갤럭시 VOL. 3는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 6.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (8, '부산영화평론', '인디아나 존스: 운명의 다이얼는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 6.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (8, '최영화리뷰어', '인디아나 존스: 운명의 다이얼는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (8, '김영화평론가', '인디아나 존스: 운명의 다이얼는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (8, '시네마스코프', '인디아나 존스: 운명의 다이얼 강력 추천합니다! 올해 본 영화 중 최고였어요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (8, '한국영화평론가', '인디아나 존스: 운명의 다이얼는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 6.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (8, '한국영화평론가', '인디아나 존스: 운명의 다이얼는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (8, '이무비크리틱', '올해 최고의 영화 중 하나라고 생각합니다. 인디아나 존스: 운명의 다이얼 정말 볼만해요.', 6.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (8, '부산영화평론', '인디아나 존스: 운명의 다이얼, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 6.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (8, '정시네필', '완성도 높은 작품입니다. 인디아나 존스: 운명의 다이얼의 모든 요소가 조화롭게 어우러져 있어요.', 6.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (8, '시네마스코프', '인디아나 존스: 운명의 다이얼의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (9, '한국영화평론가', '분노의 질주: 라이드 오어 다이는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 6.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (9, '최영화리뷰어', '분노의 질주: 라이드 오어 다이의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 6.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (9, '서울영화리뷰', '분노의 질주: 라이드 오어 다이의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (9, '박시네마리뷰', '분노의 질주: 라이드 오어 다이는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (9, '한국영화평론가', '기대 이상의 작품이었어요. 분노의 질주: 라이드 오어 다이는 시간 가는 줄 모르고 봤네요.', 6.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (9, '최영화리뷰어', '분노의 질주: 라이드 오어 다이, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (9, '최영화리뷰어', '분노의 질주: 라이드 오어 다이의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (9, '부산영화평론', '분노의 질주: 라이드 오어 다이는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 6.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (9, '김영화평론가', '분노의 질주: 라이드 오어 다이의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (9, '김영화평론가', '완성도 높은 작품입니다. 분노의 질주: 라이드 오어 다이의 모든 요소가 조화롭게 어우러져 있어요.', 6.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (10, '박시네마리뷰', '완성도 높은 작품입니다. 더 슈퍼 마리오 브라더스 무비의 모든 요소가 조화롭게 어우러져 있어요.', 8.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (10, '정시네필', '더 슈퍼 마리오 브라더스 무비의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (10, '이무비크리틱', '완성도 높은 작품입니다. 더 슈퍼 마리오 브라더스 무비의 모든 요소가 조화롭게 어우러져 있어요.', 9.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (10, '이무비크리틱', '올해 최고의 영화 중 하나라고 생각합니다. 더 슈퍼 마리오 브라더스 무비 정말 볼만해요.', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (10, '부산영화평론', '더 슈퍼 마리오 브라더스 무비 강력 추천합니다! 올해 본 영화 중 최고였어요.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (10, '서울영화리뷰', '기대 이상의 작품이었어요. 더 슈퍼 마리오 브라더스 무비는 시간 가는 줄 모르고 봤네요.', 9.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (11, '김영화평론가', '존 윅 4는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (11, '한국영화평론가', '존 윅 4는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 6.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (11, '이무비크리틱', '기대 이상의 작품이었어요. 존 윅 4는 시간 가는 줄 모르고 봤네요.', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (11, '영화저널리스트', '기대 이상의 작품이었어요. 존 윅 4는 시간 가는 줄 모르고 봤네요.', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (11, '박시네마리뷰', '기대 이상의 작품이었어요. 존 윅 4는 시간 가는 줄 모르고 봤네요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (12, '시네마스코프', '오펜하이머 강력 추천합니다! 올해 본 영화 중 최고였어요.', 8.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (12, '부산영화평론', '오펜하이머는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (12, '이무비크리틱', '오펜하이머는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (12, '이무비크리틱', '오펜하이머, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 6.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (12, '한국영화평론가', '오펜하이머 강력 추천합니다! 올해 본 영화 중 최고였어요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (12, '한국영화평론가', '기대 이상의 작품이었어요. 오펜하이머는 시간 가는 줄 모르고 봤네요.', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (13, '영화저널리스트', '완성도 높은 작품입니다. 바비의 모든 요소가 조화롭게 어우러져 있어요.', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (13, '시네마스코프', '바비, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (13, '김영화평론가', '바비, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 9.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (13, '한국영화평론가', '기대 이상의 작품이었어요. 바비는 시간 가는 줄 모르고 봤네요.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (14, '한국영화평론가', '올해 최고의 영화 중 하나라고 생각합니다. 탑건: 매버릭 정말 볼만해요.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (14, '김영화평론가', '탑건: 매버릭는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (14, '영화저널리스트', '탑건: 매버릭는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (14, '부산영화평론', '완성도 높은 작품입니다. 탑건: 매버릭의 모든 요소가 조화롭게 어우러져 있어요.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (14, '최영화리뷰어', '탑건: 매버릭, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (14, '최영화리뷰어', '탑건: 매버릭는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (14, '최영화리뷰어', '탑건: 매버릭는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (14, '정시네필', '완성도 높은 작품입니다. 탑건: 매버릭의 모든 요소가 조화롭게 어우러져 있어요.', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (15, '부산영화평론', '완성도 높은 작품입니다. 토르: 러브 앤 썬더의 모든 요소가 조화롭게 어우러져 있어요.', 7.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (15, '정시네필', '올해 최고의 영화 중 하나라고 생각합니다. 토르: 러브 앤 썬더 정말 볼만해요.', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (15, '박시네마리뷰', '토르: 러브 앤 썬더 강력 추천합니다! 올해 본 영화 중 최고였어요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (15, '김영화평론가', '기대 이상의 작품이었어요. 토르: 러브 앤 썬더는 시간 가는 줄 모르고 봤네요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (15, '김영화평론가', '토르: 러브 앤 썬더의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (15, '박시네마리뷰', '토르: 러브 앤 썬더 강력 추천합니다! 올해 본 영화 중 최고였어요.', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (16, '서울영화리뷰', '기대 이상의 작품이었어요. 닥터 스트레인지: 대혼돈의 멀티버스는 시간 가는 줄 모르고 봤네요.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (16, '정시네필', '닥터 스트레인지: 대혼돈의 멀티버스, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (16, '이무비크리틱', '기대 이상의 작품이었어요. 닥터 스트레인지: 대혼돈의 멀티버스는 시간 가는 줄 모르고 봤네요.', 8.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (16, '서울영화리뷰', '닥터 스트레인지: 대혼돈의 멀티버스는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 9.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (16, '시네마스코프', '닥터 스트레인지: 대혼돈의 멀티버스는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (17, '서울영화리뷰', '미니언즈: 라이즈 오브 그루의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 9.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (17, '한국영화평론가', '미니언즈: 라이즈 오브 그루, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (17, '영화저널리스트', '미니언즈: 라이즈 오브 그루는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (17, '정시네필', '미니언즈: 라이즈 오브 그루 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (17, '박시네마리뷰', '미니언즈: 라이즈 오브 그루는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (17, '박시네마리뷰', '미니언즈: 라이즈 오브 그루 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (18, '최영화리뷰어', '올해 최고의 영화 중 하나라고 생각합니다. 엘비스 정말 볼만해요.', 6.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (18, '박시네마리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 엘비스 정말 볼만해요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (18, '이무비크리틱', '엘비스의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (18, '시네마스코프', '완성도 높은 작품입니다. 엘비스의 모든 요소가 조화롭게 어우러져 있어요.', 6.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (18, '최영화리뷰어', '엘비스의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (19, '최영화리뷰어', '쥬라기 월드: 도미니언의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (19, '영화저널리스트', '올해 최고의 영화 중 하나라고 생각합니다. 쥬라기 월드: 도미니언 정말 볼만해요.', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (19, '서울영화리뷰', '쥬라기 월드: 도미니언의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 6.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (19, '서울영화리뷰', '완성도 높은 작품입니다. 쥬라기 월드: 도미니언의 모든 요소가 조화롭게 어우러져 있어요.', 7.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (19, '한국영화평론가', '올해 최고의 영화 중 하나라고 생각합니다. 쥬라기 월드: 도미니언 정말 볼만해요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (20, '정시네필', '범죄도시2의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (20, '시네마스코프', '기대 이상의 작품이었어요. 범죄도시2는 시간 가는 줄 모르고 봤네요.', 9.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (20, '박시네마리뷰', '범죄도시2는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 9.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (20, '박시네마리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 범죄도시2 정말 볼만해요.', 8.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (20, '시네마스코프', '올해 최고의 영화 중 하나라고 생각합니다. 범죄도시2 정말 볼만해요.', 9.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (20, '한국영화평론가', '기대 이상의 작품이었어요. 범죄도시2는 시간 가는 줄 모르고 봤네요.', 8.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (20, '박시네마리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 범죄도시2 정말 볼만해요.', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (20, '시네마스코프', '범죄도시2 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (20, '김영화평론가', '범죄도시2의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (20, '이무비크리틱', '범죄도시2는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 9.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (21, '박시네마리뷰', '헤어질 결심의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (21, '서울영화리뷰', '헤어질 결심, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (21, '부산영화평론', '헤어질 결심는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 6.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (21, '이무비크리틱', '헤어질 결심 강력 추천합니다! 올해 본 영화 중 최고였어요.', 7.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (21, '이무비크리틱', '헤어질 결심, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (21, '부산영화평론', '헤어질 결심는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (22, '이무비크리틱', '한산: 용의 출현는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (22, '서울영화리뷰', '한산: 용의 출현의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (22, '최영화리뷰어', '올해 최고의 영화 중 하나라고 생각합니다. 한산: 용의 출현 정말 볼만해요.', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (22, '최영화리뷰어', '완성도 높은 작품입니다. 한산: 용의 출현의 모든 요소가 조화롭게 어우러져 있어요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (22, '한국영화평론가', '한산: 용의 출현의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 6.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (22, '정시네필', '기대 이상의 작품이었어요. 한산: 용의 출현는 시간 가는 줄 모르고 봤네요.', 7.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (22, '이무비크리틱', '한산: 용의 출현는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (22, '시네마스코프', '한산: 용의 출현, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 6.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (22, '박시네마리뷰', '완성도 높은 작품입니다. 한산: 용의 출현의 모든 요소가 조화롭게 어우러져 있어요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (22, '최영화리뷰어', '한산: 용의 출현 강력 추천합니다! 올해 본 영화 중 최고였어요.', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (23, '이무비크리틱', '완성도 높은 작품입니다. 브로커의 모든 요소가 조화롭게 어우러져 있어요.', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (23, '부산영화평론', '브로커는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 6.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (23, '박시네마리뷰', '브로커는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (23, '한국영화평론가', '브로커 강력 추천합니다! 올해 본 영화 중 최고였어요.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (23, '김영화평론가', '완성도 높은 작품입니다. 브로커의 모든 요소가 조화롭게 어우러져 있어요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (23, '한국영화평론가', '기대 이상의 작품이었어요. 브로커는 시간 가는 줄 모르고 봤네요.', 8.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (23, '한국영화평론가', '브로커의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 6.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (23, '부산영화평론', '완성도 높은 작품입니다. 브로커의 모든 요소가 조화롭게 어우러져 있어요.', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (23, '부산영화평론', '완성도 높은 작품입니다. 브로커의 모든 요소가 조화롭게 어우러져 있어요.', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (24, '최영화리뷰어', '기대 이상의 작품이었어요. 스파이더맨: 노 웨이 홈는 시간 가는 줄 모르고 봤네요.', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (24, '이무비크리틱', '스파이더맨: 노 웨이 홈는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (24, '한국영화평론가', '완성도 높은 작품입니다. 스파이더맨: 노 웨이 홈의 모든 요소가 조화롭게 어우러져 있어요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (24, '시네마스코프', '스파이더맨: 노 웨이 홈 강력 추천합니다! 올해 본 영화 중 최고였어요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (24, '정시네필', '스파이더맨: 노 웨이 홈는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (25, '박시네마리뷰', '듄, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (25, '시네마스코프', '기대 이상의 작품이었어요. 듄는 시간 가는 줄 모르고 봤네요.', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (25, '영화저널리스트', '듄는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (25, '영화저널리스트', '기대 이상의 작품이었어요. 듄는 시간 가는 줄 모르고 봤네요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (25, '영화저널리스트', '올해 최고의 영화 중 하나라고 생각합니다. 듄 정말 볼만해요.', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (25, '영화저널리스트', '듄는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (25, '최영화리뷰어', '듄의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 6.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (25, '김영화평론가', '듄는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (25, '한국영화평론가', '듄는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (26, '서울영화리뷰', '기대 이상의 작품이었어요. 007 노 타임 투 다이는 시간 가는 줄 모르고 봤네요.', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (26, '한국영화평론가', '기대 이상의 작품이었어요. 007 노 타임 투 다이는 시간 가는 줄 모르고 봤네요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (26, '부산영화평론', '완성도 높은 작품입니다. 007 노 타임 투 다이의 모든 요소가 조화롭게 어우러져 있어요.', 8.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (26, '최영화리뷰어', '007 노 타임 투 다이, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 6.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (27, '서울영화리뷰', '분노의 질주: 더 얼티메이트의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 6.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (27, '김영화평론가', '올해 최고의 영화 중 하나라고 생각합니다. 분노의 질주: 더 얼티메이트 정말 볼만해요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (27, '정시네필', '올해 최고의 영화 중 하나라고 생각합니다. 분노의 질주: 더 얼티메이트 정말 볼만해요.', 7.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (27, '영화저널리스트', '올해 최고의 영화 중 하나라고 생각합니다. 분노의 질주: 더 얼티메이트 정말 볼만해요.', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (27, '한국영화평론가', '분노의 질주: 더 얼티메이트 강력 추천합니다! 올해 본 영화 중 최고였어요.', 6.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (27, '이무비크리틱', '완성도 높은 작품입니다. 분노의 질주: 더 얼티메이트의 모든 요소가 조화롭게 어우러져 있어요.', 7.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (27, '서울영화리뷰', '분노의 질주: 더 얼티메이트는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (27, '부산영화평론', '분노의 질주: 더 얼티메이트, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 6.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (28, '박시네마리뷰', '이터널스의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (28, '이무비크리틱', '기대 이상의 작품이었어요. 이터널스는 시간 가는 줄 모르고 봤네요.', 8.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (28, '영화저널리스트', '이터널스 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (28, '서울영화리뷰', '기대 이상의 작품이었어요. 이터널스는 시간 가는 줄 모르고 봤네요.', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (28, '박시네마리뷰', '이터널스는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (28, '한국영화평론가', '이터널스의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (28, '박시네마리뷰', '이터널스는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (28, '김영화평론가', '이터널스의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (28, '정시네필', '이터널스, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (28, '시네마스코프', '이터널스는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (29, '시네마스코프', '베놈 2: 렛 데어 비 카니지의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (29, '정시네필', '베놈 2: 렛 데어 비 카니지 강력 추천합니다! 올해 본 영화 중 최고였어요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (29, '이무비크리틱', '베놈 2: 렛 데어 비 카니지, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (29, '김영화평론가', '완성도 높은 작품입니다. 베놈 2: 렛 데어 비 카니지의 모든 요소가 조화롭게 어우러져 있어요.', 9.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (29, '이무비크리틱', '올해 최고의 영화 중 하나라고 생각합니다. 베놈 2: 렛 데어 비 카니지 정말 볼만해요.', 8.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (29, '서울영화리뷰', '베놈 2: 렛 데어 비 카니지, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (29, '이무비크리틱', '완성도 높은 작품입니다. 베놈 2: 렛 데어 비 카니지의 모든 요소가 조화롭게 어우러져 있어요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (29, '시네마스코프', '베놈 2: 렛 데어 비 카니지는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (29, '최영화리뷰어', '기대 이상의 작품이었어요. 베놈 2: 렛 데어 비 카니지는 시간 가는 줄 모르고 봤네요.', 8.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (29, '서울영화리뷰', '베놈 2: 렛 데어 비 카니지는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 9.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (30, '서울영화리뷰', '완성도 높은 작품입니다. 매트릭스 4: 리저렉션의 모든 요소가 조화롭게 어우러져 있어요.', 9.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (30, '이무비크리틱', '매트릭스 4: 리저렉션는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 9.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (30, '김영화평론가', '매트릭스 4: 리저렉션는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (30, '최영화리뷰어', '매트릭스 4: 리저렉션의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (30, '영화저널리스트', '매트릭스 4: 리저렉션는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 9.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (30, '시네마스코프', '매트릭스 4: 리저렉션, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 9.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (30, '정시네필', '완성도 높은 작품입니다. 매트릭스 4: 리저렉션의 모든 요소가 조화롭게 어우러져 있어요.', 8.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (30, '최영화리뷰어', '올해 최고의 영화 중 하나라고 생각합니다. 매트릭스 4: 리저렉션 정말 볼만해요.', 9.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (31, '최영화리뷰어', '기생충 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (31, '김영화평론가', '완성도 높은 작품입니다. 기생충의 모든 요소가 조화롭게 어우러져 있어요.', 8.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (31, '서울영화리뷰', '기생충의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (31, '시네마스코프', '기생충, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (31, '김영화평론가', '완성도 높은 작품입니다. 기생충의 모든 요소가 조화롭게 어우러져 있어요.', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (31, '한국영화평론가', '기대 이상의 작품이었어요. 기생충는 시간 가는 줄 모르고 봤네요.', 9.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (31, '정시네필', '기생충의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 9.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (31, '이무비크리틱', '기대 이상의 작품이었어요. 기생충는 시간 가는 줄 모르고 봤네요.', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (31, '이무비크리틱', '기생충의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (32, '영화저널리스트', '완성도 높은 작품입니다. 미나리의 모든 요소가 조화롭게 어우러져 있어요.', 7.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (32, '최영화리뷰어', '미나리는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (32, '영화저널리스트', '기대 이상의 작품이었어요. 미나리는 시간 가는 줄 모르고 봤네요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (32, '정시네필', '미나리 강력 추천합니다! 올해 본 영화 중 최고였어요.', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (32, '김영화평론가', '미나리는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (32, '부산영화평론', '미나리는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (32, '영화저널리스트', '미나리는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (32, '영화저널리스트', '기대 이상의 작품이었어요. 미나리는 시간 가는 줄 모르고 봤네요.', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (33, '김영화평론가', '모가디슈는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (33, '시네마스코프', '모가디슈, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (33, '박시네마리뷰', '모가디슈는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 9.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (33, '김영화평론가', '모가디슈는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 9.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (33, '이무비크리틱', '완성도 높은 작품입니다. 모가디슈의 모든 요소가 조화롭게 어우러져 있어요.', 9.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (33, '박시네마리뷰', '모가디슈 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (33, '한국영화평론가', '올해 최고의 영화 중 하나라고 생각합니다. 모가디슈 정말 볼만해요.', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (33, '정시네필', '완성도 높은 작품입니다. 모가디슈의 모든 요소가 조화롭게 어우러져 있어요.', 9.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (33, '정시네필', '모가디슈는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 9.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (33, '최영화리뷰어', '올해 최고의 영화 중 하나라고 생각합니다. 모가디슈 정말 볼만해요.', 9.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (34, '최영화리뷰어', '어벤져스: 엔드게임는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (34, '김영화평론가', '올해 최고의 영화 중 하나라고 생각합니다. 어벤져스: 엔드게임 정말 볼만해요.', 9.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (34, '한국영화평론가', '어벤져스: 엔드게임 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (34, '이무비크리틱', '기대 이상의 작품이었어요. 어벤져스: 엔드게임는 시간 가는 줄 모르고 봤네요.', 8.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (34, '이무비크리틱', '완성도 높은 작품입니다. 어벤져스: 엔드게임의 모든 요소가 조화롭게 어우러져 있어요.', 8.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (34, '박시네마리뷰', '어벤져스: 엔드게임, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (34, '부산영화평론', '어벤져스: 엔드게임의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 9.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (35, '시네마스코프', '기대 이상의 작품이었어요. 겨울왕국 2는 시간 가는 줄 모르고 봤네요.', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (35, '정시네필', '겨울왕국 2 강력 추천합니다! 올해 본 영화 중 최고였어요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (35, '한국영화평론가', '올해 최고의 영화 중 하나라고 생각합니다. 겨울왕국 2 정말 볼만해요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (35, '김영화평론가', '겨울왕국 2는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (35, '서울영화리뷰', '겨울왕국 2, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (35, '최영화리뷰어', '겨울왕국 2는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (35, '이무비크리틱', '겨울왕국 2, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (36, '서울영화리뷰', '남산의 부장들의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (36, '한국영화평론가', '남산의 부장들는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (36, '정시네필', '남산의 부장들의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (36, '정시네필', '남산의 부장들는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (37, '부산영화평론', '완성도 높은 작품입니다. 테넷의 모든 요소가 조화롭게 어우러져 있어요.', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (37, '한국영화평론가', '테넷, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 6.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (37, '한국영화평론가', '기대 이상의 작품이었어요. 테넷는 시간 가는 줄 모르고 봤네요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (37, '영화저널리스트', '기대 이상의 작품이었어요. 테넷는 시간 가는 줄 모르고 봤네요.', 7.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (37, '시네마스코프', '테넷는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 6.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (37, '영화저널리스트', '테넷는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (38, '이무비크리틱', '기대 이상의 작품이었어요. 원더 우먼 1984는 시간 가는 줄 모르고 봤네요.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (38, '박시네마리뷰', '원더 우먼 1984는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (38, '최영화리뷰어', '완성도 높은 작품입니다. 원더 우먼 1984의 모든 요소가 조화롭게 어우러져 있어요.', 9.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (38, '부산영화평론', '올해 최고의 영화 중 하나라고 생각합니다. 원더 우먼 1984 정말 볼만해요.', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (38, '영화저널리스트', '원더 우먼 1984의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (38, '김영화평론가', '원더 우먼 1984는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (39, '김영화평론가', '기대 이상의 작품이었어요. 블랙 위도우는 시간 가는 줄 모르고 봤네요.', 9.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (39, '영화저널리스트', '블랙 위도우 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (39, '시네마스코프', '올해 최고의 영화 중 하나라고 생각합니다. 블랙 위도우 정말 볼만해요.', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (39, '정시네필', '블랙 위도우는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 9.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (39, '박시네마리뷰', '블랙 위도우의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 9.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (40, '박시네마리뷰', '기대 이상의 작품이었어요. 샹치와 텐 링즈의 전설는 시간 가는 줄 모르고 봤네요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (40, '이무비크리틱', '샹치와 텐 링즈의 전설의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (40, '부산영화평론', '기대 이상의 작품이었어요. 샹치와 텐 링즈의 전설는 시간 가는 줄 모르고 봤네요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (40, '박시네마리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 샹치와 텐 링즈의 전설 정말 볼만해요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (40, '김영화평론가', '샹치와 텐 링즈의 전설, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (40, '시네마스코프', '완성도 높은 작품입니다. 샹치와 텐 링즈의 전설의 모든 요소가 조화롭게 어우러져 있어요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (40, '최영화리뷰어', '샹치와 텐 링즈의 전설는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (40, '최영화리뷰어', '샹치와 텐 링즈의 전설, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (41, '박시네마리뷰', '올드보이 강력 추천합니다! 올해 본 영화 중 최고였어요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (41, '김영화평론가', '올드보이는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 9.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (41, '박시네마리뷰', '기대 이상의 작품이었어요. 올드보이는 시간 가는 줄 모르고 봤네요.', 8.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (41, '김영화평론가', '올드보이의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (41, '정시네필', '올드보이 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (42, '시네마스코프', '올해 최고의 영화 중 하나라고 생각합니다. 아가씨 정말 볼만해요.', 6.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (42, '최영화리뷰어', '완성도 높은 작품입니다. 아가씨의 모든 요소가 조화롭게 어우러져 있어요.', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (42, '부산영화평론', '아가씨, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (42, '정시네필', '아가씨, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (42, '한국영화평론가', '기대 이상의 작품이었어요. 아가씨는 시간 가는 줄 모르고 봤네요.', 7.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (42, '정시네필', '아가씨는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (42, '김영화평론가', '아가씨 강력 추천합니다! 올해 본 영화 중 최고였어요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (43, '영화저널리스트', '곡성, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 9.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (43, '최영화리뷰어', '올해 최고의 영화 중 하나라고 생각합니다. 곡성 정말 볼만해요.', 9.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (43, '한국영화평론가', '곡성는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (43, '최영화리뷰어', '올해 최고의 영화 중 하나라고 생각합니다. 곡성 정말 볼만해요.', 9.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (43, '부산영화평론', '곡성는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (43, '박시네마리뷰', '곡성는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (43, '최영화리뷰어', '곡성는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (43, '최영화리뷰어', '곡성의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (44, '박시네마리뷰', '마더의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 9.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (44, '한국영화평론가', '마더는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 9.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (44, '정시네필', '마더의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (44, '박시네마리뷰', '마더 강력 추천합니다! 올해 본 영화 중 최고였어요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (44, '시네마스코프', '올해 최고의 영화 중 하나라고 생각합니다. 마더 정말 볼만해요.', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (44, '박시네마리뷰', '마더는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (44, '박시네마리뷰', '기대 이상의 작품이었어요. 마더는 시간 가는 줄 모르고 봤네요.', 9.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (44, '시네마스코프', '완성도 높은 작품입니다. 마더의 모든 요소가 조화롭게 어우러져 있어요.', 9.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (45, '서울영화리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 추격자 정말 볼만해요.', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (45, '김영화평론가', '추격자의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (45, '부산영화평론', '기대 이상의 작품이었어요. 추격자는 시간 가는 줄 모르고 봤네요.', 8.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (45, '최영화리뷰어', '기대 이상의 작품이었어요. 추격자는 시간 가는 줄 모르고 봤네요.', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (45, '이무비크리틱', '기대 이상의 작품이었어요. 추격자는 시간 가는 줄 모르고 봤네요.', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (45, '시네마스코프', '추격자는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (45, '서울영화리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 추격자 정말 볼만해요.', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (45, '김영화평론가', '추격자는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (45, '최영화리뷰어', '완성도 높은 작품입니다. 추격자의 모든 요소가 조화롭게 어우러져 있어요.', 7.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (46, '박시네마리뷰', '기대 이상의 작품이었어요. 악마를 보았다는 시간 가는 줄 모르고 봤네요.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (46, '서울영화리뷰', '완성도 높은 작품입니다. 악마를 보았다의 모든 요소가 조화롭게 어우러져 있어요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (46, '최영화리뷰어', '악마를 보았다는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (46, '정시네필', '악마를 보았다, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 9.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (46, '이무비크리틱', '악마를 보았다, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (46, '김영화평론가', '악마를 보았다의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (46, '정시네필', '올해 최고의 영화 중 하나라고 생각합니다. 악마를 보았다 정말 볼만해요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (47, '서울영화리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 신세계 정말 볼만해요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (47, '영화저널리스트', '기대 이상의 작품이었어요. 신세계는 시간 가는 줄 모르고 봤네요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (47, '시네마스코프', '신세계는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (47, '서울영화리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 신세계 정말 볼만해요.', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (48, '영화저널리스트', '베테랑는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (48, '영화저널리스트', '베테랑, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 9.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (48, '이무비크리틱', '베테랑의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (48, '최영화리뷰어', '기대 이상의 작품이었어요. 베테랑는 시간 가는 줄 모르고 봤네요.', 9.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (48, '시네마스코프', '올해 최고의 영화 중 하나라고 생각합니다. 베테랑 정말 볼만해요.', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (48, '김영화평론가', '베테랑의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (48, '최영화리뷰어', '베테랑는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (49, '박시네마리뷰', '터널는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (49, '영화저널리스트', '기대 이상의 작품이었어요. 터널는 시간 가는 줄 모르고 봤네요.', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (49, '영화저널리스트', '터널 강력 추천합니다! 올해 본 영화 중 최고였어요.', 8.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (49, '시네마스코프', '터널는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (49, '김영화평론가', '터널는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (49, '서울영화리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 터널 정말 볼만해요.', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (50, '김영화평론가', '올해 최고의 영화 중 하나라고 생각합니다. 1987 정말 볼만해요.', 6.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (50, '시네마스코프', '올해 최고의 영화 중 하나라고 생각합니다. 1987 정말 볼만해요.', 7.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (50, '최영화리뷰어', '1987는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (50, '영화저널리스트', '1987의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (50, '박시네마리뷰', '1987의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 6.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (50, '영화저널리스트', '완성도 높은 작품입니다. 1987의 모든 요소가 조화롭게 어우러져 있어요.', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (50, '시네마스코프', '1987는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 6.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (50, '서울영화리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 1987 정말 볼만해요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (50, '서울영화리뷰', '완성도 높은 작품입니다. 1987의 모든 요소가 조화롭게 어우러져 있어요.', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (50, '영화저널리스트', '1987 강력 추천합니다! 올해 본 영화 중 최고였어요.', 6.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (51, '시네마스코프', '기대 이상의 작품이었어요. 택시운전사는 시간 가는 줄 모르고 봤네요.', 7.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (51, '박시네마리뷰', '기대 이상의 작품이었어요. 택시운전사는 시간 가는 줄 모르고 봤네요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (51, '영화저널리스트', '택시운전사의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (51, '정시네필', '택시운전사의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (51, '정시네필', '기대 이상의 작품이었어요. 택시운전사는 시간 가는 줄 모르고 봤네요.', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (51, '부산영화평론', '올해 최고의 영화 중 하나라고 생각합니다. 택시운전사 정말 볼만해요.', 6.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (52, '박시네마리뷰', '신과함께-죄와 벌는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (52, '서울영화리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 신과함께-죄와 벌 정말 볼만해요.', 8.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (52, '한국영화평론가', '신과함께-죄와 벌는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (52, '영화저널리스트', '신과함께-죄와 벌는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (53, '시네마스코프', '완성도 높은 작품입니다. 극한직업의 모든 요소가 조화롭게 어우러져 있어요.', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (53, '서울영화리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 극한직업 정말 볼만해요.', 6.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (53, '박시네마리뷰', '극한직업, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (53, '김영화평론가', '기대 이상의 작품이었어요. 극한직업는 시간 가는 줄 모르고 봤네요.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (53, '이무비크리틱', '극한직업, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (54, '최영화리뷰어', '기대 이상의 작품이었어요. 82년생 김지영는 시간 가는 줄 모르고 봤네요.', 8.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (54, '정시네필', '82년생 김지영, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 9.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (54, '박시네마리뷰', '82년생 김지영는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 9.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (54, '정시네필', '기대 이상의 작품이었어요. 82년생 김지영는 시간 가는 줄 모르고 봤네요.', 9.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (54, '정시네필', '82년생 김지영 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (54, '시네마스코프', '82년생 김지영의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (54, '한국영화평론가', '82년생 김지영는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 9.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (54, '최영화리뷰어', '올해 최고의 영화 중 하나라고 생각합니다. 82년생 김지영 정말 볼만해요.', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (54, '영화저널리스트', '기대 이상의 작품이었어요. 82년생 김지영는 시간 가는 줄 모르고 봤네요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (55, '박시네마리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 반도 정말 볼만해요.', 7.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (55, '김영화평론가', '완성도 높은 작품입니다. 반도의 모든 요소가 조화롭게 어우러져 있어요.', 9.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (55, '정시네필', '완성도 높은 작품입니다. 반도의 모든 요소가 조화롭게 어우러져 있어요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (55, '한국영화평론가', '반도 강력 추천합니다! 올해 본 영화 중 최고였어요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (55, '시네마스코프', '반도는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (55, '시네마스코프', '기대 이상의 작품이었어요. 반도는 시간 가는 줄 모르고 봤네요.', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (55, '정시네필', '올해 최고의 영화 중 하나라고 생각합니다. 반도 정말 볼만해요.', 8.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (56, '영화저널리스트', '승리호 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (56, '부산영화평론', '기대 이상의 작품이었어요. 승리호는 시간 가는 줄 모르고 봤네요.', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (56, '정시네필', '승리호의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (56, '부산영화평론', '승리호는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (56, '한국영화평론가', '승리호는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (56, '한국영화평론가', '승리호 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (56, '한국영화평론가', '올해 최고의 영화 중 하나라고 생각합니다. 승리호 정말 볼만해요.', 8.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (57, '박시네마리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 기적 정말 볼만해요.', 6.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (57, '시네마스코프', '기적는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (57, '시네마스코프', '기적 강력 추천합니다! 올해 본 영화 중 최고였어요.', 6.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (57, '영화저널리스트', '기적는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 6.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (57, '최영화리뷰어', '기적 강력 추천합니다! 올해 본 영화 중 최고였어요.', 7.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (57, '정시네필', '기대 이상의 작품이었어요. 기적는 시간 가는 줄 모르고 봤네요.', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (58, '서울영화리뷰', '연애 빠진 로맨스의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 9.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (58, '서울영화리뷰', '연애 빠진 로맨스는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (58, '부산영화평론', '연애 빠진 로맨스의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (58, '정시네필', '연애 빠진 로맨스는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (58, '김영화평론가', '연애 빠진 로맨스는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (58, '정시네필', '연애 빠진 로맨스, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (58, '한국영화평론가', '완성도 높은 작품입니다. 연애 빠진 로맨스의 모든 요소가 조화롭게 어우러져 있어요.', 8.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (59, '시네마스코프', '마녀2 강력 추천합니다! 올해 본 영화 중 최고였어요.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (59, '서울영화리뷰', '마녀2의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 9.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (59, '영화저널리스트', '마녀2는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (59, '부산영화평론', '마녀2, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 9.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (59, '영화저널리스트', '마녀2는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (60, '영화저널리스트', '올해 최고의 영화 중 하나라고 생각합니다. 외계+인 1부 정말 볼만해요.', 6.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (60, '박시네마리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 외계+인 1부 정말 볼만해요.', 6.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (60, '이무비크리틱', '올해 최고의 영화 중 하나라고 생각합니다. 외계+인 1부 정말 볼만해요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (60, '한국영화평론가', '외계+인 1부는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 6.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (60, '서울영화리뷰', '외계+인 1부의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (60, '정시네필', '외계+인 1부 강력 추천합니다! 올해 본 영화 중 최고였어요.', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (60, '최영화리뷰어', '외계+인 1부는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 6.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (60, '한국영화평론가', '기대 이상의 작품이었어요. 외계+인 1부는 시간 가는 줄 모르고 봤네요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (61, '한국영화평론가', '인생은 아름다워 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (61, '시네마스코프', '인생은 아름다워는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (61, '정시네필', '올해 최고의 영화 중 하나라고 생각합니다. 인생은 아름다워 정말 볼만해요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (61, '박시네마리뷰', '인생은 아름다워, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (61, '이무비크리틱', '인생은 아름다워, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (61, '부산영화평론', '올해 최고의 영화 중 하나라고 생각합니다. 인생은 아름다워 정말 볼만해요.', 9.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (61, '박시네마리뷰', '올해 최고의 영화 중 하나라고 생각합니다. 인생은 아름다워 정말 볼만해요.', 9.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (61, '서울영화리뷰', '인생은 아름다워는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 9.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (61, '영화저널리스트', '올해 최고의 영화 중 하나라고 생각합니다. 인생은 아름다워 정말 볼만해요.', 9.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (61, '영화저널리스트', '올해 최고의 영화 중 하나라고 생각합니다. 인생은 아름다워 정말 볼만해요.', 9.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (62, '영화저널리스트', '헌트의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (62, '박시네마리뷰', '헌트, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 7.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (62, '영화저널리스트', '헌트는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (62, '박시네마리뷰', '헌트는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 7.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (62, '박시네마리뷰', '기대 이상의 작품이었어요. 헌트는 시간 가는 줄 모르고 봤네요.', 8.6, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (62, '부산영화평론', '헌트 강력 추천합니다! 올해 본 영화 중 최고였어요.', 8.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (62, '한국영화평론가', '헌트는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 7.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (63, '이무비크리틱', '완성도 높은 작품입니다. 결백의 모든 요소가 조화롭게 어우러져 있어요.', 8.3, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (63, '박시네마리뷰', '결백의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (63, '정시네필', '결백의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 9.2, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (63, '영화저널리스트', '결백의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (63, '최영화리뷰어', '결백는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (63, '부산영화평론', '올해 최고의 영화 중 하나라고 생각합니다. 결백 정말 볼만해요.', 7.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (63, '부산영화평론', '완성도 높은 작품입니다. 결백의 모든 요소가 조화롭게 어우러져 있어요.', 9.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (64, '이무비크리틱', '아이캔스피크는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 8.1, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (64, '최영화리뷰어', '아이캔스피크의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (64, '부산영화평론', '완성도 높은 작품입니다. 아이캔스피크의 모든 요소가 조화롭게 어우러져 있어요.', 9.4, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (64, '김영화평론가', '아이캔스피크, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 8.5, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (64, '최영화리뷰어', '아이캔스피크 강력 추천합니다! 올해 본 영화 중 최고였어요.', 9.7, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (64, '한국영화평론가', '아이캔스피크는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 9.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (64, '부산영화평론', '아이캔스피크의 연출과 연기가 정말 인상깊었습니다. 꼭 보세요!', 8.9, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (64, '이무비크리틱', '아이캔스피크는 예상보다 훨씬 재미있고 감동적이었습니다. 추천!', 8.8, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (64, '서울영화리뷰', '아이캔스피크는 정말 훌륭한 작품입니다. 스토리, 연출, 연기 모든 면에서 완성도가 높아요.', 10.0, '네이버 영화');
INSERT INTO critic_reviews (movie_id, critic_name, review_text, rating, source) VALUES (64, '정시네필', '아이캔스피크, 감동적인 스토리와 뛰어난 영상미가 조화를 이룬 수작입니다.', 9.7, '네이버 영화');
